# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Inside Project
      run: pwd
    - name: change Dir  
      run: cd /home/runner/work/dotnet-core-playwright-framework/dotnet-core-playwright-framework
    - name: Restore dependencies
      run: dotnet restore
      working-directory: /home/runner/work/dotnet-core-playwright-framework/dotnet-core-playwright-framework
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
